DROP TABLE Project.magazine;
DROP TABLE Project.sale_transaction;
DROP TABLE Project.product;
DROP TABLE Project.category;
DROP TABLE Project.vip CASCADE;
DROP TABLE Project.customer CASCADE;
DROP TABLE Project.basket;
DROP TABLE Project.brand;
DROP TABLE Project.department;
DROP TABLE Project.employee CASCADE;
DROP TABLE Project.supplier;
DROP TABLE Project.store;
DROP TABLE Project.customer_data;
DROP TABLE Project.employee_data;


DROP VIEW PRODUCTS;
DROP VIEW CATEGORIES;
DROP VIEW DEPARTMENTS;
DROP VIEW BRANDS;
DROP VIEW SUPPLIERS;
DROP VIEW CUSTOMERS;
DROP VIEW EMPLOYEES;


DROP SCHEMA Project;